<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        // async函数的返回值是promise对象,此promise对象的结果由async函数执行的返回值决定
        // await 必须写在async函数中,但async函数可以没有await
        // async function fn () {
        //     return 1;
        //     // return Promise.reject(1)
        //     // throw 1
        //     // return new Promise((resolve, reject) => {
        //     //     setTimeout(() => {
        //     //         resolve(1)
        //     //     }, 100)
        //     // })
        // }
        // result是一个promise
        const result = fn();
        console.log('fn', result);

        result.then(
            value => {
                console.log('resolve', value)
            },
            reason => {
                console.log('reject', reason)
                // throw 2
            }
        ).catch(e => {
            console.log('catch', e)
        })

        function fn1() {

        }

        function fn2() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    // resolve(2)
                    reject(2)
                }, 100)
            })
        }

        function fn3() {
            return 3;
        }

        async function fn4() {
            const value2 = await fn3(); // await右侧表达式不是promise,得到的是有侧函数的结果
            // try {
            //     value = await fn2(); // await右侧表达式是promise,得到的结果是promise成功时返回的value
            // } catch (e) {
            //     console.log('catch', e) // await右侧表达式是promise,用catch获得promise失败时返回的value
            // }
            // const value = await fn2();
            console.log('fn3', value2)
        }

        try {
            const value = fn4();
            console.log('try', value);
        } catch (E) {
            console.log('catch', E)
        }
    </script>
</body>
</html>